### ISSUE TITLE
File cleanup

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#14]
There are a lot of instances such as the `Metacalibration/mcal-scripts/` folder where there are multiple repeated files with slight differences like `ngmix_fit_superbit.py`, `ngmix_fit_superbit2.py`, `ngmix_fit_superbit3.py`. A lot of these probably came from various one-off tests, but we should either give these more descriptive file names if we want to keep them or remove them if they are no longer useful. Otherwise when @mcclearyj is gone it will be difficult to tell what is potentially useful or just clutter.

**Comment by mcclearyj** [comment]
Very much agree. I have also found several bugs in ngmix_fit_superbit3.py; this will be addressed in a separate GitHub issue.

**Comment by mcclearyj** [comment]
Update: I have created a new [metacal-reorg](https://github.com/superbit-collaboration/superbit-metacal/tree/metacal-reorg) branch to begin cleanup.

**Comment by mcclearyj** [comment]
Since we are working through the PR associated with #31 let's revisit this issue once #31 has been successfully merged

**Comment by mcclearyj** [comment]
Created new branch `issue14` to remove unnecessary files, requesting review through pull request (#43 ). Deleted branch `metacal_reorg`  referenced below as it has significantly diverged from `main`

> Update: I have created a new [metacal-reorg](https://github.com/superbit-collaboration/superbit-metacal/tree/metacal-reorg) branch to begin cleanup.
