### ISSUE TITLE
Flagging bugs to be fixed in ngmix_fit_superbit3.py

### ISSUE THREAD

**Issue by mcclearyj** [superbit-collaboration/superbit-metacal#15]
There are several enhancements and bug fixes to be made to the superbit_ngmix_fit3.py shape measurement script:

1. This "debugging" reference and function in Line 149 should be removed: 

https://github.com/superbit-collaboration/superbit-metacal/blob/master/Metacalibration/mcal-scripts/ngmix_fit_superbit3.py#L149

2. In line 164, the PSF wcs should be `ngmix.jacobian.DiagonalJacobian(scale=psf_pixel_scale,x=(this_psf.shape[0]-1)/2,y=(this_psf.shape[1]-1)/2)`

[https://github.com/superbit-collaboration/superbit-metacal/blob/ee5cd3b34fb3de2e93917bc1c3d594d3c3e3bb18/Metacalibration/mcal-scripts/ngmix_fit_superbit3.py#L164]

It's also not 100% clear whether defining a Jacobian from scratch for the PSF `Observation` is the correct approach. Should the default MEDS object Jacobian be used?

3. This section of the code (lines 203-216) is unnecessary and possibly wrong. `ngmix` has a `ngmix.bootstrap.MaxMetacalBootstrapper()` class that does the bootstrapping for each of `noshear, {1/2}{p/m}` 
https://github.com/superbit-collaboration/superbit-metacal/blob/master/Metacalibration/mcal-scripts/ngmix_fit_superbit3.py#L203

Moreover, the ngmix fit centroids and `g1/g2/T` are not the same when computed with `mcb.fit_max()` and `mcb.fit_metacal()`. This should be fixed immediately.

4. The `get_mcalib_shears()` and `make_output_table` methods would be much simpler and less prone to error if `mcr`, the dictionary containing the results of the `MaxMetacalBootstrapper`, were just passed to `make_output_table(outfilename, gmix, mcal,identifying)` (line 285) directly.

5.  Line 453 `model_image = gmix.make_image(image_cutout.shape,jacobian=jj)` should be changed to 
`
max_gmix = maxfit.get_convolved_gmix()
gmix_galsim=max_gmix.make_galsim_object()
gmix_galsim_im = gmix_galsim_im.drawImage(nx=cutout_avg.shape[0],ny=cutout_avg.shape[1],scale=pixel_scale)
gmix_galsim_im.drawImage(nx=cutout_avg.shape[0],ny=cutout_avg.shape[1],wcs=jacobian)
`

6. Line 458 is double-wrong. Not only does `gmix.get_cen()` output center coordinates in **arcseconds** not pixels as assumed here, but the centroid is returned in `[row,col]` format so that should be `y,x = gmix.get_cen()` and not `x,y`! Suggest changing 458 to `y,x = gmix.get_cen(); y/=pixel_scale; x/=pixel_scale`

https://github.com/superbit-collaboration/superbit-metacal/blob/master/Metacalibration/mcal-scripts/ngmix_fit_superbit3.py#L458

7. Line 461 will fail without a warning if the directory `diagnostic_images` doesn't exist. Suggest adding statement like 
`
    imsavedir=os.path.join(homedir,'diagnostics_plots')    
    if not os.path.isdir(imsavedir):
            cmd='mkdir -p %s' % imsavedir
            os.system(cmd)
    im_file_name='diagnostics-ngmix3-'+str(i)+'.png'
    im_file=os.path.join(imsavedir,imfile_name)

    fig.savefig(im_file)
    plt.close(fig)
`
https://github.com/superbit-collaboration/superbit-metacal/blob/master/Metacalibration/mcal-scripts/ngmix_fit_superbit3.py#L461

**Comment by mcclearyj** [comment]
In the most recently pushed version of [ngmix_fit_superbit3.py,](https://github.com/superbit-collaboration/superbit-metacal/blob/ff5dbf693d8215d6ba6728183d0514f02791eef4/Metacalibration/mcal-scripts/ngmix_fit_superbit3.py) have been address. Summary of changes:

**Comment by mcclearyj** [comment]
@sweverett I will leave this issue open in case you have any comments or encounter problems.

**Comment by sweverett** [comment]
My current problem running the script is actually the same as before the updates. The call to `get_prior()` fails because we are not passing an `rng` instance explicitly [here](https://github.com/superbit-collaboration/superbit-metacal/blob/master/Metacalibration/mcal-scripts/ngmix_fit_superbit3.py#L70).

I assume this is due to a change in `ngmix`. I have version `2.0.0` while your environment has `1.3.8`. I have no idea how important the difference between these versions is, though I think it may be worth updating the code to work with the newest version just in case some of the changes are important. I remember finding a `ngmix` bug while doing Balrog tests for example where the coefficients used to distribute the relative flux between the Gaussians was wrong. Who knows what other bugs may be in there.

**Comment by mcclearyj** [comment]
Closing issue as required changes have been committed and significant refactoring has occured
