### ISSUE TITLE
Do mock images need (0,0) origin?

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#16]
Right now, the mock images are explicitly set to have a (0,0) origin [here](https://github.com/superbit-collaboration/superbit-metacal/blob/master/GalSim/mock_superBIT_data.py#L602) in `mock_superbit_data.py`. The WCS for this image assumes a (1,1) origin (confirmed by looking at the fits file with DS9), so we should check if this is causing an unwanted offset between the true positions. GalSim is pretty smart so it may be handling it correctly behind the scenes and converting anyway before saving, but we should test this.

**Comment by sweverett** [comment]
Looking at the single exposures vs. the input positions there does indeed seem to be a roughly (1,1) pixel offset, but removing `setOrigin(0,0)` did not appear to fix the issue...

**Comment by mcclearyj** [comment]
@sweverett I believe that you solved this problem with your last commit in the Medsmaker directory, so I am marking this issue as closed!
