### ISSUE TITLE
Check if new pipe.py import scheme broke utils functions

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#29]
I haven't checked this for the current repo yet, but using a similar module setup as this repo + replacing the utils import from `import utils` -> `import {repo-name}.utils as utils` broke the utils directory conventions & helper functions. We should check if this happened for `superbit_lensing` as well.

**Comment by mcclearyj** [comment]
What's the correct way to check this?

**Comment by sweverett** [comment]
I just did a few tests that seem to indicate that this is not an issue for this repo. See #27, and the `pipe.py` test runs successfully. This may just be an issue with the other repo `setup.py` file.

**Comment by sweverett** [comment]
Re-opening this as I have discovered what the original problem is. I setup the new module structure & `setup.py` in part so that we could run things robustly outside of the module directories, say make a test file in the `tests/` dir. These files would just have to do absolute imports for things, e.g. `import superbit_lensing.utils as utils`.

The issue I ran into in my other project was that having relative imports in the module dir (e.g. `import utils` inside `superbit_lensing/pipe.py`) would break when doing the abs import in the test dir such as `import superbi_lensing.pipe as pipe`. I think I wasn't able to reproduce the issue because I hand't recently rebuilt the module with `setup.py`.

The solution to all of this appears to be that we should make all of the local relative imports _explicit_. So in `superbit_lensing/pipe.py`, `import utils` becomes `from . import utils`. This seems to make the built module understand how to connect all of this.

**Comment by sweverett** [comment]
Well setting the explicit relative import fixed the testing infrastructure ability to build & call things from a different directory, but now calling the `main()` function in the module directly seems to break. I am very confused at this point. The best solution may be to do absolute imports everywhere and fix the `utils.py` helper functions to get the base, module, and test dirs to account for the fact that the `__file__` will no longer point to the repo

**Comment by mcclearyj** [comment]
Does this issue need to be updated after the latest round of refactoring?

**Comment by sweverett** [comment]
I believe this was fixed a while ago, closing
