### ISSUE TITLE
Running superbit-lensing locally 

### ISSUE THREAD

**Issue by mcclearyj** [superbit-collaboration/superbit-metacal#30]
I experimented with running the refactored `superbit-lensing` repository on my current work laptop (MacOS Big Sur/Anaconda3 python distribution; the `conda` environment is shown below). Below is a list of issues and lessons learned from setting up the `superbit-lensing` pipeline and processing an existing simulated galaxy cluster observation. 

Basic installation and test run:

- If I try to run `pipe.py` _within_ the `superbit_lensing`, the `superbit_lensing/galsim` module is loaded instead of the expected `GalSim` code. So I have to run `$python superbit_lensing/pipe.py`. This is probably a local environment issue; I couldn't figure out how to successfully move `./` to the end of the Python path. 
- `>>> python pipe.py` with default config file expects the existence of a directory named 'test' within `superbit_lensing`. This may throw off other users.
- Both `>>python pipe.py -v/-vb` are unrecognized arguments, though this argument doesn't appear to be referenced in [the top-level readme](https://github.com/superbit-collaboration/superbit-metacal/blob/242132c3e592be0c0d2eb5332338c5463e1c2ceb/README.md)
- User-specific locations of COSMOS galaxy catalogs used by `GalSim` need to be updated within the configuration files `superbit-metacal/superbit_lensing/galsim/config_files`. I will add a note in the `galsim` module README file. 
- The following lines in `mock_superBIT_data.py` assume that the COSMOS catalogs are stored in the same directory as other catalogs used in the simulation:
https://github.com/superbit-collaboration/superbit-metacal/blob/242132c3e592be0c0d2eb5332338c5463e1c2ceb/superbit_lensing/galsim/mock_superBIT_data.py#L645-L649. It may be more robust to specify separate `datadir` and `cosmosdir` here (cf. `issue30-jmac_local` branch).
- The `pipe_test/plots/galsim/compare_truth_tables.pdf` check plot just has blank subplots. 
- When running `superbit-lensing/medsmaker`, the `PSFEx` PDF check plots end up in the top level directory. Added small change to `medsmaker/superbit/medsmaker_mocks.py` to also move PDF check plots to the `PSFEx` working directory.
- In running`superbit-lensing/metacal`, no metacalibration diagnostics plots are generated or saved. These plots are useful in debugging and it would be good to figure out how to output them again. Additionally, the `mcal_fitting.log` doesn't seem to give much information about the run, and ends up in the top level directory regardless of options specified in the configuration files. 

Non-default run using pre-existing simulations:

- There's a small typo in top-level README on how to call `superbit-lensing`: it should be `pipe = SuperBITPipeline(config_file, log)` not `pipe = SuperBitPipeline(config_file, log)`
- Perhaps this will be obvious to others, but it took me ages to figure out that I needed to write a `SuperBITPipeline` configuration file from scratch, rather than just somehow modifying `pipe.py`. I'm suggesting a small change to README to make this explicit, as well as linking to an example. 
- It also took me a while to figure out that the user  needs to call `SuperBITPipeline` in an `IPython session` or from a wrapper script like `superbit-lensing/process_all.py` (`issue30-jmac_local` branch). Suggesting a small change to README to make this explicit for other inexperienced users. 
- Again, may be obvious to others, but to run `SuperBITPipeline` on existing simulations, the user needs to update the `mock_dir` and `fname_base` arguments to reflect the mock `GalSim` images being used. Also, it's now made explicit in my sample config file that `fname_base` refers to the simulated (or real!) image root name, which wasn't obvious to me before.
- The default behavior of the `medsmaker` module is to store the output `MEDS` and coadd files in the same directory as the mock images, with no options to change the output directory. I have added a required `outdir` option to `process_mocks.py` and `pipe.py`, though perhaps this could be downgraded to optional. 
- `medsmaker` assumes the existence of mask and weight files with locations specified in `process_mocks.py` and `medsmaker_mocks.py`. We should figure out the best way to do this. 
- I have yet to run the new `ngmix_fit_superbit3.py` on an HPCC. A cheap parallelization could be achieved for `metacalibration/ in pipeline v1.0 by submitting an array of jobs to an HPCC, each with automatically generated `start` and `end` specified in the command line. Hopefully the new multiprocessing scheme makes this faster and more efficient!

**Comment by sweverett** [comment]
Leaving some comments or responses as I see them, though it will take time before I respond to them all.

> - If I try to run pipe.py within the superbit_lensing, the superbit_lensing/galsim module is loaded instead of the expected GalSim code. So I have to run $python superbit_lensing/pipe.py. This is probably a local environment issue; I couldn't figure out how to successfully move ./ to the end of the Python path.

Did you run `python setup.py install` from the root repo directory? That is the thing that sets up the python module. It is designed specifically so that you do not ever have to touch your Python path. If you did, then there is just something up with the `utils.get_test_dir()`, `utils.get_base_dir()`, etc. functions. I am able to run from other directories on my machine after running the setup file.

**Comment by mcclearyj** [comment]
Thanks for the detailed response. Given what you're saying, it seems like by and large my issues were mostly due to being unfamiliar with the way `SuperBITPipeline` should be invoked, as well as the way the config files should be handled. When I finally understood what was happening, the refactored pipeline is seamless and easy to use.
