### ISSUE TITLE
Integrate PIFF into pipeline for PSF modeling

### ISSUE THREAD

**Issue by mcclearyj** [superbit-collaboration/superbit-metacal#45]
Testing on simulated SuperBIT exposures shows that PIFF performs at least as well as (if not better) than PSFEx for modeling the SuperBIT PSF. PIFF has also been shown to avoid the size bias that affects PSFEx models. For these reasons, the pipeline should start using PIFF for PSF modeling instead of the existing PSFEx. 

List of steps, in order of pipeline calls

- [x] Find new way to automatically create a star catalog, preferably using catalog quantities and without matching to the truth file. An inelegant but functional solution would be first running PSFEx to create a star catalog and feeding that into PIFF
- [x] Invoke PIFF on multiple images simultaneously (see note below)
- [x] Find a way to "trick" the `meds` module into accepting a PIFF model for `MEDS` creation instead of a PSFEx model. 
- [x] Alternatively, render PIFF PSF model on the fly in `ngmix_fit_superbit3.py` 

Note: It appears beneficial to the final PSF solution (smaller `rho` statistics) for PIFF to be run on several images simultaneously. PIFF is generally computationally expensive, and a "multifit" mode on 18 exposures is even more computationally expensive -- probably beyond the capabilities of a laptop. A test job run on an HPCC took ~56 minutes to fit PIFF solutions to 18 exposures simultaneously.

**Comment by sweverett** [comment]
RE the stellar selection - I recommend that we follow what was done in the PIFF paper, which is actually the same as DES SV & Y1. Basically:
- Use mag vs. size diagram using `MAG_AUTO` and `SIGMA` of a best fit Gaussian profile using AM
- Select on `0.9 < CLASS_STAR < 1`
- Set mag & size limits based on saturated stars and merger of star & galaxy locus. To do this precisely, we could probably just ask for the "algorithm" that they keep mentioning in all 3 papers but never explicitly explain
Here is what the selection looked like for an example CCD chip:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/8742179/157144442-bdf6498b-15ad-48ca-9019-562197372fcc.png">

**Comment by mcclearyj** [comment]
Agreed -- this shouldn't be challenging to implement.

**Comment by mcclearyj** [comment]
I successfully incorporated PIFF into `medsmaker_mocks.py` but at the expense of modifying the `meds` package's `maker.py` script. `maker.py` expects that supplied psf files have a `get_rec` function that is available in `psfex` objects but not `piff`. 

Since requiring users to download a fork of `meds` is impractical, @sweverett suggested adding an "extender" in `medsmaker_mocks.BITMeasurement()` that will add a `get_rec` method  to `piff` PSF objects. This has been implemented here: XXX

I also did a bit of `medsmaker_mocks.py` code cleanup: 

- Both `_make_piff_model` and `make_psfex_model` use the same code to invoke Source Extractor to make individual exposure catalogs
- `make_catalog` (which is really make _coadd image and catalog_) has a very similar call to Source Extractor 
- These Source Extractor calls have now been integrated into `BITMeasurement._run_sextractor()`
- There is now a separate `BITMeasurement.make_exposure_catalogs()` method as well

**Comment by mcclearyj** [comment]
We discussed the fact that the "piff adaptor" functionality isn't actually an adaptor, as the `PiffExtender` object no longer functions like a `piff` object. @sweverett looked at the `piff` code, and it seems like a non-trivial fix. Since the current iteration at least runs to completion, I suggest leaving the `piff_extender` function in its current condition and creating a separate "enhancement" issue for later where in the interests of long-term maintainability we fix the adaptor issue.

**Comment by mcclearyj** [comment]
Since PR #47 has been merged, this issue can be closed.
