### ISSUE TITLE
Check shape error from `ngmix.pars` retrieval is correct

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#49]
Currently in `make_annular_catalog.py`, it estimates the shape noise in part by grabbing the model param variance from `pars_noshear_cov` [here](https://github.com/superbit-collaboration/superbit-metacal/blob/master/superbit_lensing/shear_profiles/make_annular_catalog.py#L209)

However, it does this by grabbing the `(0,0)` and `(1,1)` entries of the 6x6 `pars` covariance matrix. I believe these are actually the centroid positions, not the shapes. I'm still looking for absolute confirmation of this for Gaussian mcal models, but it is quite clear [here](https://github.com/superbit-collaboration/superbit-metacal/blob/master/superbit_lensing/shear_profiles/make_annular_catalog.py#L209) for BDF models:
```
class GMixBDF(GMixModel):
    """
    Gaussian mixture representing a bulge+disk with
    fixed size ratio
    Parameters
    ----------
    pars: sequence
        [c1,c2,g1,g2,T,fracdev,flux]
    TdByTe: number, optional
        Optionally set TdByTe.  Defaults to 1.0
    """
    ...
```

We should check that we are doing the right thing here, as I think this points towards a bug. We also need to identify anywhere else in the code that values are extracted from a `pars` or `pars_cov` array to make sure there are no other bugs.

https://github.com/esheldon/ngmix/blob/v1.3.9/ngmix/gmix.py#L1015

**Comment by mcclearyj** [comment]
Thanks for posting the issue, I will check on this.

**Comment by mcclearyj** [comment]
Update: this is in fact a major bug! Good catch. 

You correctly assessed that the purpose of lines like [these](https://github.com/superbit-collaboration/superbit-metacal/blob/43314cf7eaa5c0e00573e5d1fdba6155c6f3332d/superbit_lensing/shear_profiles/make_annular_catalog.py#L207) in `make_annular_catalog.py` is for shape noise estimates and also `ngmix` fit quality cuts. 

You are also correct that the `(0,0)` and `(1,1)` entries of the 6x6 `pars` covariance matrix are _centroid_ covariances not _shear_ covariances. Calls like `self.mcal['pars_cov0_2m']` should be replaced with the diagonal elements of the 4x4 shear covariance matrices for each of `{noshear, 1p, 1m, 2p, 2m}`. 

I've created a branch `issue49` to fix this bug.

At the same time as I implement the bug fix, I will also remove the unnecessary (I think) `to_list()` statements in those same lines.

**Comment by sweverett** [comment]
I believe #49 resolved this, closing
