### ISSUE TITLE
NFW redshift resampling

### ISSUE THREAD

**Issue by mcclearyj** [superbit-collaboration/superbit-metacal#52]
The "true" NFW shear catalogs reflect the redshift distribution of the COSMOS 2015 galaxy catalog. This may differ from the redshift distribution of galaxies detected in the mock observations. Shape measurement and selection cuts change the redshift distribution further. For accurate calculation of shear bias, the reference NFW shear catalog should be resampled so that its redshift distribution matches the redshift distribution of galaxies in the final weak lensing catalog. 

This change will be implemented in a separate branch: `resample_redshift`

**Comment by sweverett** [comment]
I believe this was covered in #54, closing
