### ISSUE TITLE
Rework catalog config files for forecasting sims

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#6]
Currently, the config structure in `GalSim/mock_superBIT_data.py` assigns a `cosmosdir` for the directory of the source catalog (called `cosmos_cat`, but _not_  the included `GalSim` COSMOS catalog) separately from the cluster catalog (which actually _is_ the COSMOS catalog). I find this quite confusing, as this means that the `cosmosdir` will not point to the traditional save location for the `GalSim` COSMOS catalog download. While I could point this to `superbit-metacal/GalSim/data/` as I think @mcclearyj does, I'd rather not as it is common to use these catalogs outside of this particular project.

Instead, I propose that the `cosmosdir` points to wherever the user points `GalSim` to save the COSMOS catalogs, and we introduce a `datadir` which points to where the catalogs & files specifically for this repo are stored. It looks like this should only require a few new lines.

I'm also open to re-naming `cosmos_cat` -> something related to "sources" given the above, but without seeing much of the repo yet I'm not sure how widespread this convention is. I can also just get used to it.

**Comment by mcclearyj** [comment]
This is a good idea for sure, the current naming is a holdover from an obsolete version. I will merge your version.
