### ISSUE TITLE
Properly set multiple seeds in `galsim` submodule

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#61]
Right now, the mock galsim config takes in 4 separate seeds for the rng initialization of the noise and 3 classes of objects (stars, sources, cluster gals). However, this is not necessarily a safe practice as each rng is not guaranteed to be uncorrelated w/ the others. This problem is worse for the work currently being done in the `job-configs` branch as each of these seeds need to be automatically generated at config creation time, and many obvious ways to produce these lead to possibly correlated rng's or even duplicates (birthday problem).

The safest approach is to let `numpy` generate 4 "independent" rng's from a single master seed value. Given the docs [here](https://numpy.org/doc/stable/reference/random/parallel.html), I think our safest bet is to use `SeedSequence` with a single master seed (perhaps the local time in microseconds, `int(time.time()*1e6)`?) and then use `SeedSequence.spawn(N)` to produce `N` independent `rng` objects.

**Comment by sweverett** [comment]
In addition to the above - I think the real risk is coming up with `N` uncorrelated master seeds when automatically generating the config files for each job in `prep_jobs.py`. So this will probably have to happen at multiple places - in the config generation of each seed, and in setting 4 `rng`'s in `mock_superbit_data.py`

**Comment by mcclearyj** [comment]
I see. I am not sure that we are likely to encounter the birthday problem in our current analysis with an eight-digit random seed. Say we sample 10 clusters with 10 realizations apiece and 48 threads. 10*10*48 = 4800. Nonetheless, implementing [SeedSequence](https://numpy.org/doc/stable/reference/random/parallel.html) is both good practice and makes our analysis easier. Plus, I can imagine future users wanting to run enough realizations that the birthday problem becomes a real possibility.

**Comment by sweverett** [comment]
Well, partly I'm worried about this because Nmasses=3 x Nz=3 = 9 seems like the absolute minimum number of unique (m,z) combinations we will do (and potentially a lot more), and that is actually only an order of magnitude away from having ~99.5% chance of a duplicate seed! But the larger thing I'm worried about is having different cluster realizations set w/ master seeds that are accidentally correlated

**Comment by sweverett** [comment]
Completed by #63.
