### ISSUE TITLE
Rework file paths with configs

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#9]
Right now most file paths are hard coded for a single user. There are many alternatives we could choose, but I think it will be simplest to create configs for the user to specify relative to the repo path.  The main decision here I believe is whether we want to have separate configs for each module (GalSim, Medsmaker, etc.) or a master config that talks to each subcomponent for full runs. It looks like there are existing config structures for the modules anyway, so maybe a master config + a script that produces the requisite configs from it for each module would be helpful.

**Comment by sweverett** [comment]
Alternatively, we could set a repo path variable and do everything relative to that. This would require making standard input / output directories for each module, but I don't think that would be much of an issue

**Comment by mcclearyj** [comment]
I like the idea of configs, since the GalSim code is set up to run with a config file.

**Comment by sweverett** [comment]
This idea is now incorporated into #22 as the high-level run config.
